### PR TITLE
Airbnb Automation in Lock User

### PR DESCRIPTION
**Pull request by tylerjw**
I wrote some code to integrate an Airbnb iCal link into users to set door codes based on the last 4 digits of someone's phone number.  The settings for this are in a hidden menu.

I had a separate project for doing this and decided to integrate my code into lock-manager to be more useful to others and to allow me to use all the useful features of lock-manager with my lock along with my airbnb automation.

When enabled it checks your airbnb ical every 15 minutes and sets the door code if there is a change.  It has a checkout time so it can changeover the code in the middle of the day.  I allow instant book of my property up to 10pm of the same day and this means that if I have a same day booking the code will be set within 15min.

### CODE REVIEW

**Comment by tylerjw** [comment]
Please ignore this for now.  There is a bug in the way the checkin notify works.  Also, I should polish up my code more before/if you accept it into the repo.

**Comment by tylerjw** [comment]
After realizing that my workaround for the userCode setting did not work I put back most of my changes in lock-user.groovy and created a new child app, airbnb-user.groovy.  I also removed the checkin notification setting as that does not seem to be working.  Being able to send a notification for the checkin and then disabling the notification until the next guest is the only thing I have left to add (assuming I don't find another bug in the current implementation).

**Comment by tylerjw** [comment]
Ok, I believe this is ready for review.  I have tested it and it seems to be working correctly and I've implemented all the features I wanted for this.

**Comment by mrmarior** [comment]
Please help. I am completely new to this. 
I want to use lock manger for airbnb. 
Thanks
Mario

**Comment by tylerjw** [comment]
@mrmarior I would be happy to help you get this working for you.  Could you send me an email at tyler@weaveringrally.com.

**Comment by mrmarior** [comment]
I am going step by step. Will advise once I get lock manager running.

Thanks,
Mario Ruiz
On Oct 12, 2017, at 8:04 AM, Tyler Weaver <notifications@github.com<mailto:notifications@github.com>> wrote:

@mrmarior<https://github.com/mrmarior> I would be happy to help you get this working for you. Could you send me an email at tyler@weaveringrally.com<mailto:tyler@weaveringrally.com>.

**Comment by mrmarior** [comment]
Tyler I got as far as copy and pasting the code.
But cant figure it out after that.
Can we share screens?

Thanks

Mario


________________________________

**Comment by tylerjw** [comment]
I've added some more features and am debugging something that is causing the codes to be changed a day early.  Please do not merge this until I figure out what's causing that.

**Comment by bkalps** [comment]
@tylerjw Thanks so much for putting together this code! I have been using Lock Manager for about 4 months and have been manually entering each Airbnb guest’s information. I hacked your lock manager code updates into my Smartthings (like @4amy did) and pasted your airbnb-user.groovy code into a new smartapp. I’m going to keep manually adding my Airbnb guests as users in Lock Manager for a week to compare with the automation and make sure I don’t experience any bugs and let you know how it goes!

I tried using my Airbnb Host calendar link at first (which didn't work) and found the correct way to point to the iCal, which might save future users some time:

1. Go to Manage Listings on airbnb.com
2. Find the listing you'd like to edit and click Manage listing
3. Above your listing preview, click Availability
4. Under Sync Calendars, select Export calendar
5. Copy and paste the Airbnb calendar link into your iCal applications

Any recommendations how to make sure I'm still tracking any updates to both ethayer's lock manager code as well as yours going forward?

**Comment by ethayer** [comment]
I'd love to include this in the app proper, but I do not have access to any AirBnB ical documents to test on.

LockManger 2.0 is close to being released and works on a little but of a different concept code-wise.  Instead of editing the main document, a node process called gulp watches documents in the source directory and combines them together to create a single file.

I've found this to be easier to maintain and organize.

Going forward I would really like to offer this feature in my web API for LockManager, though I suspect I'll have to create an AirBnB account to mess with things.

Thanks for your work on this, and if you're willing to re-write this on the 2.0 app, I could help with that process.  It shouldn't be too much of a re-write, just re-organizing things into main.groovy and creating a new AirBnB source file in the gulp manifest.

Good work!

**Comment by tylerjw** [comment]
@ethayer I would be happy to do the work to integrate with the next version of this.  I have been successfully using this with my airbnb.  I would be happy to provide you with a ical url to my airbnb for your testing purposes.  Send me a message and I'll give it to you.

**Comment by chantalew** [comment]
Hello, I’m a newbie here. I got the Lock-Manager to work last night and would love to know how I can do the iCal integration to manage my Airbnb guests check in. Is there a step by step like the Lock-Manager installation that I can follow along?  Thx.

**Comment by tylerjw** [comment]
I submitted a pull request for the beta-2 branch.  I'm closing this as I'm no longer using this code and do not want to support it.

**Pull request closed without merging**
