### PR TITLE
airbnb automation in 2.0

### PR DESCRIPTION
**Pull request by tylerjw**
Here is the code to get airbnb automation working with the beta.  I will switch my places over to this to begin testing it.  So far it appears to be working.  If you need a ical link for testing send me a email.

I like the way the new code is laid out.  It allowed me to make these changes without duplicating code from the user app that is the same.

### CODE REVIEW

**Comment by ethayer** [comment]
Is this good to go?  Looks great.  Thank you for following my conventions.  Bravo!

**Comment by tylerjw** [comment]
Not yet.  I want to write some tests for it to verify it works as expected.  I’ve just not had time to do that.  Also, I think there might be a bug in how it sets codes although I’ve not been able to reproduce the bug.

**Comment by tylerjw** [comment]
@ethayer I believe this is now ready.  I finally got around to tracking down the bug that was causing it to not set the code in the lock.  The issue had to do with how I was using state and how lock code setting changed in the beta.  By using atomicState for the userCode I was able to make this work.

**Comment by tylerjw** [comment]
@blu3dye found some more issues with this code I should work out before you merge.

**Comment by chantalew** [comment]
Hello, I'm wondering if this Airbnb module has been updated?  I'm getting some error messages. Thanks.

**Comment by blu3dye** [comment]
@chantalew, i've been using a modified version of it for a over a month now. my branch works for my use cases. i did run into 1 issue once though when the code wouldn't set. not sure why though.

what error messages are you running into?

**Comment by sportgd** [comment]
Does this automatically pull information from airbnb and create lock codes? Sounds like an awesome idea!

**Comment by blu3dye** [comment]
@sportgd, yes it does. it scrapes the calendar entry to pull name, phone number, and check in/out dates.

**Comment by sportgd** [comment]
Thanks for the response! I'm going to have to check into this! I currently have the old lock-manager running on my rental apartment but will be adding a second rental soon and automation will really help.

**Comment by chantalew** [comment]
It did not work as I had hoped.  Somehow my install was not doing it automatically.  I had to log into the app and do a save each time and when there is no guest, I get error messages.  The developer is no longer providing support.  I had to switch to another app and paid for it -RBoy.com.  And its working fine now except for one little issue.  When I have one guest who booked both rooms, an error occurs when the same code is being pushed to the lock, which is ok.  But when that guest left and another code needs to be pushed, that did not occur automatically and i had to reset it manually.

**Comment by tylerjw** [comment]
After much testing I believe this is good for integration into the branch.  I have used this over the last year and a half on 3 properties and with every generation of the smartthings controller.  I just checked in a couple changes that include the hub name in the notifications.  I believe the one bug I struggled with where it wouldn't set sometimes had to do with the distance of my hub from my lock and placing a powered device between the two fixed the issue.  Occasionally (1/30 code changes) it fails to set because it times out while parsing ical data.  If this happens enough times it won't set the code and I have to go in and kick it by saving the airbnb user.  I haven't found a solution to that issue.

**Comment by tylerjw** [comment]
I know I keep going back and forth on this but I think this is in a good state now.  I found a solution to the bug that was keeping it from being set and made some changes to help reduce timeouts.  There is still one outstanding issue that push notifications have to be enabled in users and Airbnb automation for them to be complete.  I haven't figure out why this is yet.

**Comment by tylerjw** [comment]
Airbnb broke this today :(.  The data from the ical service now looks like this (note the lack of information on the guest, including a phone number):

`BEGIN:VEVENT
DTEND;VALUE=DATE:20190707
DTSTART;VALUE=DATE:20190703
UID:1418fb94e984-949318a8c98af73f8aa69b4a04d3042d@airbnb.com
DESCRIPTION:Not Available\nReservation: https://www.airbnb.com/reservatio
 n/itinerary?code=HMB9JEJCTM
SUMMARY:Airbnb (HMB9JEJCTM)
END:VEVENT`

**Comment by blu3dye** [comment]
well that sucks. i use airbnb's notes for my homeaway entries and input them manually in to airbnb's calendar notes. as long as the data is in the notes for name and phone number, it should still be able to parse it. i'll test it later tonight or tomorrow.

**Comment by chantalew** [comment]
Totally sucks. I tried to call AirBnb support and got no where. 

Sent from Chantale's iPhone
(218)296-6488 google voice

**Comment by tylerjw** [comment]
I have reached out to Airbnb and hopefully, they can provide us a better solution.  Until then I'm working on a workaround but it'll take a while to get working.

**Comment by blu3dye** [comment]
using NAME: <name> PHONE: <xxx-xxx-xxxx> in the notes no longer works as well.  may be we can do a get call using the new link in the description.

**Comment by blu3dye** [comment]
My best guess is this is due to security concerns. The ical pulls weren't secure. The weblink in the description requires the owner to login to get the guest details. This is far more secure than what they originally had.

**Comment by tylerjw** [comment]
@blu3dye I agree.  This now requires login to get at the data.  I'm working on a workaround that'll do this the correct way.  I'll update here when I get it working.

**Comment by chantalew** [comment]
Thank you!

Sent from Chantale's iPhone
(218)296-6488 google voice

**Comment by tylerjw** [comment]
Closing as I no longer use this and have migrated to a different solution.

**Pull request closed without merging**
